RB444.Admin/Controllers/OtherSettingController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using RB444.Core.IServices;
using RB444.Core.ServiceHelper;
using RB444.Data.Entities;
using RB444.Model.ViewModel;
using RB444.Models.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace RB444.Admin.Controllers
{
    public class OtherSettingController : Controller
    {
        private readonly IRequestServices _requestServices;
        private readonly IConfiguration _configuration;
        private readonly UserManager<Users> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public OtherSettingController(IRequestServices requestServices, IConfiguration configuration, UserManager<Users> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _requestServices = requestServices;
            _configuration = configuration;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        #region News settings
        public async Task<ActionResult> News()
        {
            var user = JsonConvert.DeserializeObject<Users>(Request.Cookies["loginUserDetail"]);
            ViewBag.LoginUser = user;

            var commonModel = await _requestServices.GetAsync<CommonReturnResponse>(String.Format("{0}Common/GetAllNews", _configuration["ApiKeyUrl"]));
            var newsList = jsonParser.ParsJson<List<News>>(Convert.ToString(commonModel.Data));

            return View(newsList);
        }

        [HttpPost]
        public async Task<ActionResult> AddUpdatedCreateNews(News model)
        {
            CommonReturnResponse commonModel = null;
            try
            {
                commonModel = await _requestServices.PostAsync<News, CommonReturnResponse>(string.Format("{0}OtherSetting/SaveNews", _configuration["ApiKeyUrl"]), model);
                var data = JsonConvert.SerializeObject(commonModel);
                return Json(data);
            }
            catch (Exception ex)
            {
                var data = new CommonReturnResponse()
                {
                    IsSuccess = false,
                    Message = ex.Message
                };
                return Json(JsonConvert.SerializeObject(data));
            }
        }

        [HttpPost]
        public async Task<ActionResult> DeleteNews(int id)
        {
            CommonReturnResponse commonModel = null;
            try
            {
                commonModel = await _requestServices.PostAsync<int, CommonReturnResponse>(string.Format("{0}OtherSetting/DeleteNews", _configuration["ApiKeyUrl"]), id);
                var data = JsonConvert.SerializeObject(commonModel);
                return Json(data);
            }
            catch (Exception ex)
            {
                var data = new CommonReturnResponse()
                {
                    IsSuccess = false,
                    Message = ex.Message
                };
                return Json(JsonConvert.SerializeObject(data));
            }
        }

        #endregion

        #region Slider Images settings
        public async Task<ActionResult> SliderImages()
        {
            var user = JsonConvert.DeserializeObject<Users>(Request.Cookies["loginUserDetail"]);
            ViewBag.LoginUser = user;

            var commonModel = await _requestServices.GetAsync<CommonReturnResponse>(String.Format("{0}Common/GetAllSliders", _configuration["ApiKeyUrl"]));
            var sliderList = jsonParser.ParsJson<List<Slider>>(Convert.ToString(commonModel.Data));
            return View(sliderList);
        }

        [HttpPost]
        public async Task<ActionResult> AddUpdatedSliderImages()
        {
            CommonReturnResponse commonModel = null;
            Slider model = new Slider();
            try
            {
                bool status = Convert.ToBoolean(Request.Form["Status"]);
                var file = Request.Form != null && Request.Form.Files.Count > 0 ? Request.Form.Files : null;

                model.FileName = UploadedFile(file, "SliderImages");
                model.FilePath = "SliderImages/" + model.FileName;
                model.Status = status;

                commonModel = await _requestServices.PostAsync<Slider, CommonReturnResponse>(string.Format("{0}OtherSetting/SaveSlider", _configuration["ApiKeyUrl"]), model);
                var data = JsonConvert.SerializeObject(commonModel);
                return Json(data);
            }
            catch (Exception ex)
            {
                var data = new CommonReturnResponse()
                {
                    IsSuccess = false,
                    Message = ex.Message
                };
                return Json(JsonConvert.SerializeObject(data));
            }
        }

        [HttpPost]
        public async Task<ActionResult> ChangeStatus(int id, bool status, int api)
        {
            CommonReturnResponse commonModel = null;
            try
            {
                if (api == 1)
                {
                    Logo model = new Logo();
                    model.Id = id;
                    model.Status = status;
                    commonModel = await _requestServices.PostAsync<Logo, CommonReturnResponse>(string.Format("{0}OtherSetting/SaveLogo", _configuration["ApiKeyUrl"]), model);
                    var data = JsonConvert.SerializeObject(commonModel);
                    return Json(data);
                }
                else
                {
                    Slider model = new Slider();
                    model.Id = id;
                    model.Status = status;
                    commonModel = await _requestServices.PostAsync<Slider, CommonReturnResponse>(string.Format("{0}OtherSetting/SaveSlider", _configuration["ApiKeyUrl"]), model);
                    var data = JsonConvert.SerializeObject(commonModel);
                    return Json(data);
                }
            }
            catch (Exception ex)
            {
                var data = new CommonReturnResponse()
                {
                    IsSuccess = false,
                    Message = ex.Message
                };
                return Json(JsonConvert.SerializeObject(data));
            }
        }

        [HttpPost]
        public async Task<ActionResult> DeleteSlider(int id, string imagePath)
        {
            CommonReturnResponse commonModel = null;
            try
            {
                var isDelete = DeleteFile(imagePath);
                commonModel = await _requestServices.PostAsync<int, CommonReturnResponse>(string.Format("{0}OtherSetting/DeleteSlider", _configuration["ApiKeyUrl"]), id);
                var data = JsonConvert.SerializeObject(commonModel);
                return Json(data);
            }
            catch (Exception ex)
            {
                var data = new CommonReturnResponse()
                {
                    IsSuccess = false,
                    Message = ex.Message
                };
                return Json(JsonConvert.SerializeObject(data));
            }
        }

        #endregion

        #region Logo Images settings
        public async Task<ActionResult> LogoImages()
        {
            var user = JsonConvert.DeserializeObject<Users>(Request.Cookies["loginUserDetail"]);
            ViewBag.LoginUser = user;

            var commonModel = await _requestServices.GetAsync<CommonReturnResponse>(String.Format("{0}Common/GetAllLogo", _configuration["ApiKeyUrl"]));
            var LogoList = jsonParser.ParsJson<List<Logo>>(Convert.ToString(commonModel.Data));
            return View(LogoList);
        }

        [HttpPost]
        public async Task<ActionResult> AddUpdatedLogoImages()
        {
            CommonReturnResponse commonModel = null;
            Logo model = new Logo();
            try
            {
                bool status = Convert.ToBoolean(Request.Form["Status"]);
                var file = Request.Form != null && Request.Form.Files.Count > 0 ? Request.Form.Files : null;

                model.FileName = UploadedFile(file, "LogoImages");
                model.FilePath = "LogoImages/" + model.FileName;
                model.Status = status;

                commonModel = await _requestServices.PostAsync<Logo, CommonReturnResponse>(string.Format("{0}OtherSetting/SaveLogo", _configuration["ApiKeyUrl"]), model);
                var data = JsonConvert.SerializeObject(commonModel);
                return Json(data);
            }
            catch (Exception ex)
            {
                var data = new CommonReturnResponse()
                {
                    IsSuccess = false,
                    Message = ex.Message
                };
                return Json(JsonConvert.SerializeObject(data));
            }
        }

        [HttpPost]
        public async Task<ActionResult> DeleteLogo(int id, string imagePath)
        {
            CommonReturnResponse commonModel = null;
            try
            {
                var isDelete = DeleteFile(imagePath);
                commonModel = await _requestServices.PostAsync<int, CommonReturnResponse>(string.Format("{0}OtherSetting/DeleteLogo", _configuration["ApiKeyUrl"]), id);
                var data = JsonConvert.SerializeObject(commonModel);
                return Json(data);
            }
            catch (Exception ex)
            {
                var data = new CommonReturnResponse()
                {
                    IsSuccess = false,
                    Message = ex.Message
                };
                return Json(JsonConvert.SerializeObject(data));
            }
        }

        #endregion


        private string UploadedFile(IFormFileCollection imageFile, string folderName)
        {
            string uniqueFileName = null;

RB444.Admin/Views/OtherSetting/LogoImages.cshtml
@model IEnumerable<RB444.Data.Entities.Logo>
@{
    ViewData["Title"] = "LogoImages";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>Logo Images</h2>
    <div class="row p-4">
        <button class="btn btn-primary btn-sm w-auto" onclick="getRequest()">Add Logo</button>
    </div>
    <table class="sportesTbl table table-striped table-dark">
        <thead>
            <tr>
                <th>S NO.</th>
                <th>Image</th>
                <th>ACTION</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                int i = 1;
                foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@i</th>
                        <td><img style="height:50px; width:100px;" src="../@item.FilePath" /></td>
                        @if (item.Status == true)
                        {
                            <td id="Status_@item.Id" style="color:lawngreen;">
                                <a onclick="statusChange(@item.Id,false)">Active</a>
                            </td>
                        }
                        else
                        {
                            <td style="color:orangered;">
                                <a onclick="statusChange(@item.Id,true)">DeActive</a>
                            </td>
                        }

                        <td>
                            <a onclick="getRequest(@item.Id)" class="Edit"><i class="fa fa-edit"></i></a>
                        </td>
                        <td>
                            <a onclick="deleteRequest(@item.Id)"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    i++;
                }
            }
        </tbody>
    </table>
</div>

<div class="all-modals">
    <div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <form id="request-form" autocomplete="off" class="" method="post">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Logo Image</h5>
                        <button type="button" class="close" onclick="closeModel();">
                            ×
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-horizontal">
                            <div class="error" style="display:none;" id="error"></div>
                            <div class="image-input image-input-empty image-input-outline">
                                <img src="~/common/UserProfile.png" id="account-upload-img" class="image-input-wrapper" alt="profile image" />

                                <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                                    <i class="fa fa-pen icon-sm text-muted"></i>
                                    <input type="file" id="ProfileImage" name="file" hidden accept="image/*" />
                                </label>                              
                                <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow resetBtn" data-action="remove" data-toggle="tooltip" title="Remove avatar">
                                    <i class="fa fa-times "></i>
                                </span>
                            </div>
                            <div class="form-group d-flex justify-content-between align-items-center mb-75">
                                <div class="form-group d-flex justify-content-between align-items-center mb-75">
                                    <div class="col-md-12 mt-10 d-flex">
                                        <input type="checkbox" id="Status" style="width: 20px;height: 20px;">
                                        <label class="form-label ml-2" style="font-size: 20px!important;">Status</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" id="cancle" class="btn btn-light" onclick="closeModel();">Cancel</button>
                        <button type="button" id="btn-save" class="btn btn-primary font-weight-bold" onclick="return saveRequest()">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@section PageJs{
    <script src="~/js/custom.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var accountUploadImg = $('#account-upload-img');
            var accountUploadBtn = $('#ProfileImage');

            // Update user photo on click of button
            if (accountUploadBtn) {
                accountUploadBtn.on('change', function (e) {
                    var reader = new FileReader(),
                        files = e.target.files;
                    reader.onload = function () {
                        if (accountUploadImg) {
                            accountUploadImg.attr('src', reader.result);
                        }
                    };
                    reader.readAsDataURL(files[0]);
                });
            }
            // Reset Photo
            $(".resetBtn").click(function () {
                $("#ProfileImage").val("");
                accountUploadImg.attr('src', '/common/UserProfile.png');
            });
        });

        function getRequest() {
            $('#registerModal').modal('show');
        }

        function closeModel() {
            $('#registerModal').modal('hide');
        }

        function saveRequest() {
            let formdata = new FormData();
            let fileList = document.getElementById("ProfileImage").files;
            if (fileList.length > 0) {
                for (const file of fileList) {
                    formdata.append(file.name, file);
                }
                formdata.append("Status", $("#Status").prop("checked"));
                let uploadAttachmentJson = {
                    apiUrl: "@Url.Action("AddUpdatedLogoImages", "OtherSetting")",
                    postData: formdata
                }
                $(".loader").show();
                promiseAjaxPost.call(uploadAttachmentJson, false).then(
                    (res) => {
                        $(".loader").hide();
                        if (res.IsSuccess && res.Status == 200) {
                            messagePopup.responseSuccess(res.Message).then(
                                (r) => { if (r == true) { location.reload() } }
                            )
                        } else {
                            messagePopup.responseError(res.Message);
                        }
                    },
                    (err) => {
                        messagePopup.error(err.statusText);
                    }
                )
            }
            else {
                messagePopup.responseError("Please upload Image.");
            }
        }

        function deleteRequest(id) {
            const formData = new FormData();
            formData.append("id", id);

            let addRequestJson = {
                apiUrl: "@Url.Action("DeleteLogo", "OtherSetting")",
                postData: formData
            }
            $(".loader").show();
            promiseAjaxPost.call(addRequestJson, false).then(
                (res) => {
                    $(".loader").hide();
                    if (res.IsSuccess && res.Status == 200) {
                        messagePopup.responseSuccess(res.Message).then(
                            (r) => { if (r == true) { location.reload(); } }
                        )
                    } else if (res.IsSuccess && res.Status == 208) {
                        messagePopup.responseWarning(res.Message);
                    } else {
                        messagePopup.responseError(res.Message);
                    }
                },
                (err) => {
                    messagePopup.error(err.statusText);
                }
            )
            return false;
        }

        function statusChange(id, status) {
            if (id == null || id == 0) {
                return false;
            }
            const formData = new FormData();
            formData.append("id", id);
             formData.append("status", status);
             formData.append("api", 1);

            let addRequestJson = {
                apiUrl: "@Url.Action("ChangeStatus", "OtherSetting")",
                postData: formData
            }
            $(".loader").show();
            promiseAjaxPost.call(addRequestJson, false).then(
                (res) => {
                    $(".loader").hide();
                    if (res.IsSuccess && res.Status == 200) {
                        messagePopup.responseSuccess(res.Message).then(
                            (r) => { if (r == true) { location.reload(); } }
                        )
                    } else if (res.IsSuccess && res.Status == 208) {
                        messagePopup.responseWarning(res.Message);
                    } else {
                        messagePopup.responseError(res.Message);
                    }
                },
                (err) => {
                    messagePopup.error(err.statusText);
                }
            )
            return false;
        }

    </script>
}

RB444.Admin/Views/OtherSetting/News.cshtml
@model IEnumerable<RB444.Data.Entities.News>
@{
    ViewBag.Title = "News";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>News Content</h2>
    <div class="row p-4">
        <button class="btn btn-primary btn-sm w-auto" onclick="getRequest()">Create News</button>
    </div>
    <table class="sportesTbl table table-striped table-dark">
        <thead>
            <tr>
                <th>S NO.</th>
                <th>Content</th>
                <th>ACTION</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                int i = 1;
                foreach (var item in Model)
                {
                    <tr>
                        <td scope="row">@i</td>
                        <td id="NewsText_@item.Id">@item.NewsText</td>
                        @if (item.Status == true)
                        {
                            <td id="Status_@item.Id" style="color:lawngreen;">
                                Active
                            </td>
                        }
                        else
                        {
                            <td style="color:orangered;">
                                DeActive
                            </td>
                        }

                        <td>
                            <a onclick="getRequest(@item.Id)" class="Edit"><i class="fa fa-edit"></i></a>
                        </td>
                        <td>
                            <a onclick="deleteRequest(@item.Id)"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    i++;
                }
            }
        </tbody>
    </table>
</div>

<div class="all-modals">
    <div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <form id="request-form" autocomplete="off" class="" method="post">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">News</h5>
                        <button type="button" class="close" onclick="closeModel();">
                            ×
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-horizontal">
                            <div class="error" style="display:none;" id="error"></div>
                            <input type="hidden" id="idNews" value="0">
                            <div class="form-group d-flex justify-content-between align-items-center mb-75">
                                <div class="col-md-12">
                                    <textarea type="text" rows="4" style="min-width:100%" class="form-control" id="NewsText" placeholder="News Text"></textarea>
                                </div>
                            </div>
                            <div class="form-group d-flex justify-content-between align-items-center mb-75">
                                <div class="form-group d-flex justify-content-between align-items-center mb-75">
                                    <div class="col-md-12">
                                        <input type="checkbox" id="Status" />
                                        <label class="form-label">Status</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="modal-footer">
                        <button type="button" id="cancle" class="btn btn-light" onclick="closeModel();">Cancel</button>
                        <button type="button" id="btn-save" class="btn btn-primary font-weight-bold" onclick="return saveRequest()">Save</button>
                    </div>


                </form>
            </div>
        </div>
    </div>
</div>


@section PageJs{
    <script src="~/js/custom.js"></script>
    <script type="text/javascript">
        function getRequest(id = null) {
            if (id != null) {
                $("#idNews").text(id);
                $("#NewsText").val($("#NewsText_" + parseInt(id)).text());
                $("#Status").prop("checked",$("#Status_" + parseInt(id)).text().trim() === 'Active' ? true : false);
            }
            $('#registerModal').modal('show');
        }

        function closeModel() {
            $('#registerModal').modal('hide');
        }
        function saveRequest() {
            const formData = new FormData();
            formData.append("Id", $("#idNews").text());
            formData.append("NewsText", $("#NewsText").val());
            formData.append("Status", $("#Status").prop("checked"));

            let addRequestJson = {
                apiUrl: "@Url.Action("AddUpdatedCreateNews", "OtherSetting")",
                postData: formData
            }
            $(".loader").show();
            promiseAjaxPost.call(addRequestJson, false).then(
                (res) => {
                    $(".loader").hide();
                    if (res.IsSuccess && res.Status == 200) {
                        messagePopup.responseSuccess(res.Message).then(
                            (r) => { if (r == true) { location.reload(); } }
                        )
                    } else if (res.IsSuccess && res.Status == 208) {
                        messagePopup.responseWarning(res.Message);
                    } else {
                        messagePopup.responseError(res.Message);
                    }
                },
                (err) => {
                    messagePopup.error(err.statusText);
                }
            )
            return false;
        }

        function deleteRequest(id) {
            const formData = new FormData();
            formData.append("id", id);

            let addRequestJson = {
                apiUrl: "@Url.Action("DeleteNews", "OtherSetting")",
                postData: formData
            }
            $(".loader").show();
            promiseAjaxPost.call(addRequestJson, false).then(
                (res) => {
                    $(".loader").hide();
                    if (res.IsSuccess && res.Status == 200) {
                        messagePopup.responseSuccess(res.Message).then(
                            (r) => { if (r == true) { location.reload(); } }
                        )
                    } else if (res.IsSuccess && res.Status == 208) {
                        messagePopup.responseWarning(res.Message);
                    } else {
                        messagePopup.responseError(res.Message);
                    }
                },
                (err) => {
                    messagePopup.error(err.statusText);
                }
            )
            return false;
        }


    </script>
}